### PR TITLE
Add basic Identity

### PR DESCRIPTION
**Pull request by wisniewski-patryk**

### CODE REVIEW

**Review by MariuszMalec — COMMENTED** [review]
If I start app and I'm not login and than I click button "Add new employee" than I get pop "failed to insert employee" and I don't know why?
I think better is add message "Try to login or register". After login this button works properly.

**Review by MariuszMalec — COMMENTED** [review]
If I'm not logged and click remove employee I got pop that is success, emploee is removed from view but employee is not removed from database. After refresh page, employ apear again on view :-). This button works properly after login.

**Review by MariuszMalec — COMMENTED** [review]
If I click the login button without filling in email and password I get error "System.NullReferenceException". Also I get error if I set f.e wrong password.
Still not working properly, after clicking login without filling txtboxes the app is crashed.

**Review by MariuszMalec — COMMENTED** [review]
button register doesn't work

**Comment by wisniewski-patryk** [comment]
> If I start app and I click button "Add new employee" than I get pop "failed to insert employee" and I don't know why?

Are you logged in? Or you lunch it on empty database

**Review by MariuszMalec — COMMENTED** [review]
If I logout I still can remove employee.

**Comment by wisniewski-patryk** [comment]
ok, now everything works with web assembly. I handle communication in better way and use build in toast message service

**Review by MariuszMalec — COMMENTED** [review]
If I login and then logout I got pop "logout succesful" but I still see on main page button logout

**Comment by wisniewski-patryk** [comment]
> If I login and then logout I got pop "logout succesful" but I still see on main page button logout

Yeah, I still have to figure out, how to recognize user session is on.

**Comment by wisniewski-patryk** [comment]
> If I login and then logout I got pop "logout succesful" but I still see on main page button logout

fixed

**Comment by wisniewski-patryk** [comment]
Let's check newest version. Everything should works

**Comment by wisniewski-patryk** [comment]
> button register doesn't work after fill in not correct email and/or password (or without filling). I don't know why I can't register. I don't see any message error. For example, I set wrong password "1234" and I don't get any information "Passwords must be at least 6 characters." In swagger this work correctly and I see validation:-). I can only register correctly within api and swagger

fixed, but not completely. I add TODO for the future. It is not critical (UI respond what exactly is wrong).

**Comment by wisniewski-patryk** [comment]
> If I start app and I'm not logged and than I click button "Add new employee" than I get pop "failed to insert employee" and I don't know why? I think better is add message "Try to login or register". After login this button works properly.

I think more toast message can be write better :) we will check it later

**Comment by wisniewski-patryk** [comment]
> If I click the login button without filling in email and password I get error "System.NullReferenceException". Also I get error if I set f.e wrong password. Still not working properly, after clicking login without filling txtboxes the app is crashed.

fixed

**Review by MariuszMalec — APPROVED** [review]

**Pull request merged**
